### ISSUE TITLE
Dupe Bug

### ISSUE THREAD

**Issue by bigbantha** [BluSunrize/TravellersGear#14]
There is a dupe bug with the armor stand involving any Baubles items (rings, belts, amulets).
with absolutely none of the aforementioned items equipped, shift-click any Baubles item into a stand's GUI, and then immediately exit it. Reopen the stand's GUI, and you should see a copy of that item in it's appropriate spot, which you can remove from. To repeat, simply remove the item from your equipment menu, and start over. Works in both survival and creative, with ANY baubles-dependent items.

**Comment by BluSunrize** [comment]
What version of TG?

**Comment by bigbantha** [comment]
latest

**Comment by BluSunrize** [comment]
Can't reproduce. Please try with Version 1.14.6 and keep me updated.

**Comment by bigbantha** [comment]
k

**Comment by bigbantha** [comment]
Well, it's still in 1.14.6. Also, shift-clicking baubles items from your equipment menu into the armor stand (in it's GUI) will create a ghost of the item in the stand's GUI. Trying to remove it from the stand will delete it permanently.

**Comment by bigbantha** [comment]
If you need, I could make a private YouTube video on this and link it here.

**Comment by BluSunrize** [comment]
That sounds like a good idea.

**Comment by bigbantha** [comment]
okay, I'll see if fraps still runs :)
