### ISSUE TITLE
Showing items in chat

### ISSUE THREAD

**Issue by GreatOrator** [BluSunrize/TravellersGear#15]
It seems to be a rather weird occurance.

It seems when there's 2 people in the server, neither sees any shown items. When there's 3, 2 people will see each other's items, the 3rd only sees their own. When there's 4, everyone sees the items.

Now this may be related to server software (do not have a pure forge server to test) and this is using the latest version up on curseforge.

**Comment by BluSunrize** [comment]
Can't replicate this in my environment, sorry.
