### ISSUE TITLE
[Feature Request][Possible Bug] Closing the inventory with the keybinding.

### ISSUE THREAD

**Issue by SnowShock35** [BluSunrize/TravellersGear#17]
Hi Blu,
I have been really enjoying the use of Traveller's gear it's and awesome mod. However, there is one thing that bugs me slightly and that is that you cannot close the GUI with the keybinding and you have to use escape unlike the regular vanilla inventory. I'm not sure if this is a bug or a feature request or weather it's possible to add but if so It would be a nice addition to the mod in my opinion ;)
-Snow

**Comment by BluSunrize** [comment]
Ohey SnowShock! That name rings a bell =P

That'S actually a good suggestion, I'll add it with the next release =)

**Comment by SnowShock35** [comment]
Sneaky snowman is sneaky :p
Yaay I helped \o/

**Comment by BluSunrize** [comment]
It's in the new build, 1.15.7, which should already be approved on curseforge =3

**Comment by stardustrider** [comment]
Would it be possible to allow this for all other GUI containers?

**Comment by BluSunrize** [comment]
What, for those not added by my mod? No I'd rather not, because it might break other people's containers.
