### ISSUE TITLE
(Botania + Travellers + Witching Gadgets) not behaving together

### ISSUE THREAD

**Issue by LoyLT** [BluSunrize/TravellersGear#18]
http://paste.ee/p/Id11M

been trying all day to get Botania, Traveller's Gear, and Witching Gadgets working together... before 1.15.7 of Traveller's, I had to either leave out Botania or leave ot both Traveller's and Witching Gadgets.... now with Traveller's v1.15.7, i only have to leave out either Botania or Witching....

Botania{r1.5-169}
TravellersGear{1.15.7}
WitchingGadgets{1.1.2}

Can someone tell me a combination of version numbers that actually works for all three of these mods together? Or is there maybe a config value I need to change?

**Comment by BluSunrize** [comment]
It's quite simple, you need to update Botania.
Your build is outdated, and because I cannot check for the API version you are using, my mods assume that you have the Botania version with attachable cosmetics. That version has been out for quite a bit now, and since then, Vazkii has added even more cool stuff, so you should really get an upgrade =P

**Comment by LoyLT** [comment]
i have the latest botania according to http://botaniamod.net/downloads.php
and it came out March 6th according to http://www.curse.com/mc-mods/minecraft/225643-botania#t1:other-downloads

**Comment by BluSunrize** [comment]
So you are...how very odd. It's throwing an exception usually related to the fact that it cannot find the correct class. You said it works when you leave WG out?

**Comment by LoyLT** [comment]
yes.. if i take out witching, it doesn't throw the error, it lets me play....
according to the botania changelogs, the api version number since .167 should be 35

**Comment by BluSunrize** [comment]
I don't even package the API, I build on Botania as a library. I'll look into it.

**Comment by LoyLT** [comment]
I'm not positive if this is the cause or not but perhaps it will point you in the right direction... Looks like the witching core loads before botania and because it looks like you use one of the botania API files in witching it is looking there for the complete API package and that is maybe why it isn't seeing the proper functions

**Comment by LoyLT** [comment]
Well thank you for keeping me informed....
I see you've removed the bundled botania API from Witching Gadgets
I've tested with just Botania 172, Travellers 1.15.7, and Witching 1.1.3 ... boots fine now...
Guess i'll close this issue
