### ISSUE TITLE
GUI Bug

### ISSUE THREAD

**Issue by crunkazcanbe** [BluSunrize/TravellersGear#20]
Experience level bar is overlapping a slot . https://imgur.com/yDAaofs

I am using the latest version of travelers Gear as of today .

**Comment by BluSunrize** [comment]
And that's why the gui is fully configurable. You can easily change the whole layout ;D

**Comment by crunkazcanbe** [comment]
How?

**Comment by BluSunrize** [comment]
Ingame, use the command "/travellersgear gui"

**Comment by crunkazcanbe** [comment]
Thank you man!
