### ISSUE TITLE
Crafting title item

### ISSUE THREAD

**Issue by Qohelethh** [BluSunrize/TravellersGear#21]
Sorry if this isn't the right place to ask this! I can craft title scrolls, but they have no name attached to them. Is there any way to add a name to them within game? Or a config option to add new titles? Thanks!

**Comment by Alaberti** [comment]
I wonder, would putting it in an anvil and renaming it that way work?

**Comment by BluSunrize** [comment]
It does. And yeah this isn't really the place to ask this ^^
