### ISSUE TITLE
Level meter is unaligned and the tinkers canisters slot will only accept one.

### ISSUE THREAD

**Issue by l3CY** [BluSunrize/TravellersGear#23]
1.  Alignment issues. Here is an image of the nonalignment problem.  As can be seen, the level bar is under-lapped by the tinkers canister slot.  

http://i40.photobucket.com/albums/e230/SlightlyVisible/book_zpse4dmgb1s.png

2. Tinkers Canisters.  The slot which holds tinkers heart canisters will not accept more than one when clocked on with a stack.  The only way around this issues as my shift clicking in the canisters all at once.

Awesome mod.  Keep up the good work!

**Comment by BluSunrize** [comment]
1. the gui is configurable. Just move the level bar where you want it.
2. I'll look into it.
