### ISSUE TITLE
[Feature Request] Scarves

### ISSUE THREAD

**Issue by Alaberti** [BluSunrize/TravellersGear#24]
In the cloak slot. I dunno, I'm just a sucker for a nice scarf what can I say? If it could also be a thing with Witching Gadgets as well that'd be swell. See, I'm bringing out the posh vocabulary for this one.

**Comment by BluSunrize** [comment]
nice idea...kinda the same slot though.
Maybe a different mod can add scarves that go into TG's cloak slot? =P
