### ISSUE TITLE
Keybind - Issue in Multiplayer (1.16.4)

### ISSUE THREAD

**Issue by LazerusKI** [BluSunrize/TravellersGear#32]
Both keybinds have a very weird issue.

Travellers Gear Inventory - This one opens the Inventory for every player nearby. Yes, one player uses it, and everyones inventory opens.

Travelers Gear Active Abilities - This one doesnt work when there is another player nearby. The interface just doesnt show up

**Comment by BluSunrize** [comment]
Update to 1.16.5? =P
