### ISSUE TITLE
Feature Request - Customizable Vertical Offset on titles.

### ISSUE THREAD

**Issue by Aubron** [BluSunrize/TravellersGear#33]
We are using TravellersGear [on AlienMC](https://www.reddit.com/r/AlienMC/comments/3ipc3k/update_82815_more_things_to_spend_on_titles/)

And we love it. Wondering if it would be possible to have a config option to change the vertical offset of the Titles. Our case is that armourer's workshop adds fairly large head pieces, and these hide the label in some cases. Would like to have it above the nameplate for these situations, especially since this mod and armourer's just mesh so nicely in their RPG nature.

Thanks for a great mod!

PS: Sorry for using issues for feature requests - always unsure about whether or not its kosher per mod, but I did see some in the past you responded okay to.

**Comment by Aubron** [comment]
Updated all references to horizontal with vertical. Because I'm an idiot.

**Comment by BluSunrize** [comment]
atm not getting to work on this, but I'll keep it in mind when I get back to TG. It's actually a realyl good suggestion ^.^
