### ISSUE TITLE
Open all players inventories if on spawn 

### ISSUE THREAD

**Issue by axelpx** [BluSunrize/TravellersGear#34]
I don't know which mod its conflicting with (Tinker's, CustomNPCs or even some bukkit plugin (WorldGuard? Factions?)) but I have a wierd issue on the server. When player press а button to open their inventory it opens it for every player in proximity. It only happens at spawn area of the world.

**Comment by BluSunrize** [comment]
Update to the latest TG, this was fixed ages ago.

**Comment by axelpx** [comment]
I was using TravellersGear-1.7.10-1.16.4, I'll check if it fixed in the latest build.
