### ISSUE TITLE
[Request] TwoGraves support

### ISSUE THREAD

**Issue by Shahelion** [BluSunrize/TravellersGear#47]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2480388-twograves-v1-1-keeps-your-items-safe-on-death

From the mod support section: 
"If your favorite mod has an extra inventory and is not yet supported, please ask the creator of that mod to use my API. It is well documented, comes with several examples and can be implemented in less than 10 minutes. Should there be any questions I will try to help."

**Comment by BluSunrize** [comment]
I add TG items to the drop event, just like baubles. If the grave mod doesn't catch them, that's upon them to fix not me

**Comment by Shahelion** [comment]
This particular grave mod handles it differently, though. When you right-click your grave, every item goes right back into the slot it was in when you died, even Baubles and TiCon items. Anything unsupported simply falls on the ground outside the grave. If there isn't room for items to be retrieved by right-click, they stay in the grave until you make room and try again.
