### ISSUE TITLE
Server issue with ctrl+right click

### ISSUE THREAD

**Issue by SrAnthony** [BluSunrize/TravellersGear#49]
This mod need a option to disable the ctrl+rightclick on items to show it on chat, this flood all the server. You can remove this, add a cooldown or a option to disable.

**Comment by BluSunrize** [comment]
If it floods your server tell your users off? Making sure your users behave isn't my job, really isn't it? xD

**Comment by SrAnthony** [comment]
Let's say that some players don't know how to use this function and they need to be kicked or banned because of this.

**Comment by BluSunrize** [comment]
Well yeah. After 2 or 3 warnings, a kick would probably be in order, followed with a ban on accounts of further violation.
That's kinda how server administration works. The admin makes rules, and if they're not followed, appropriate measures have to be taken.

**Comment by SrAnthony** [comment]
But a disable option on config will be welcomed, I really like this mod.

**Comment by BluSunrize** [comment]
I don't plan any updates in the near future. And honestly, I really don't plan any updates at all. 1.7 is done, I might rewrite it for 1.9
