### ISSUE TITLE
Ars Magica 2 Spells in Chat

### ISSUE THREAD

**Issue by xSable** [BluSunrize/TravellersGear#51]
I'm having a problem with every server I've played with Traveller's and Ars Magica 2. Each one seems to get this same issue.

If you ctrl+click to show ANY ars magica spell in chat, and anyone hovers over it to view the item, they will crash back to launcher.

http://pastebin.com/raw/1hx3MhKJ

That's the crash report. Hopefully you can add support for Ars Magica 2.

**Comment by BluSunrize** [comment]
Issue is on AM2's side, not mine.
